title: Jobly
description: "August 2023 to June 2024"
owner_name: Aidan Lau
github_username: AidanLau10
github_repo: "joblyFrontend"
baseurl: "/joblyfrontend"
future: true
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/jm1021/alienWorld"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/time.md
  - navigation/search.html

